#!/usr/bin/env node
const config = require('../config.json');
const socket = require('socket.io');
let app = require('http').createServer();
let io = socket(app);

app.listen(config.game, () => {
  console.log(`Husky Engine Game Server listening on ${config.game}`)
});

io.on('connection', (socket) => {
    console.log(`Connection from ${socket.id}`);

    io.emit('_connected', {})

    // Handle events here //

    // Ping event
    socket.on('_ping', data => {

      // Contains uuid
      if (data.uuid) {
        console.log(`User's uuid is ${data.uuid}`);
        socket.uuid = data.uuid;
      }

      // Reply with same data
      let reply = {data: data.data};

      io.emit('_pong', reply);
    });
});
