#!/usr/bin/env node
const config = require('../config.json');
const debug  = require('debug')(config.name + ':Server');

let app   = require('http').createServer()
const io  = require('socket.io')(app)
const p2p = require('socket.io-p2p-server').Server

// Set up socket.io/webrtc
io.use(p2p)

app.listen(config.game, () => {
  console.log(`Husky Engine Game Server listening on ${config.game}`)
});

io.on('connection', (socket) => {
  console.log('Connection Received');
});
